***Installing Packages Needed for This Notebook and/or Beyond***

In [42]:
#%pip install tensorflow
#%pip install --upgrade pip
#%pip install numpy

In [43]:
import numpy as np

***Fast standard tensors definition***

In [44]:
identity_4x4 = np.eye(4)  # takes only one dimension (square matrix)
identity_4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
zero_vector_4 = np.zeros(4)
zero_vector_4

array([0., 0., 0., 0.])

In [46]:
zero_matrix_4x4 = np.zeros((4, 4))
zero_matrix_4x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
ones_matrix_4x4 = np.ones((4, 4))
ones_matrix_4x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
progression_vector = np.arange(10)
progression_vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***Linear algebra operations***

In [49]:
a = np.random.uniform(-1, 1, size = 5) + 1.0j * np.random.uniform(-1, 1, size = 5)
    # define a random complex vector from U[-1, 1] with size 5
#print("a =",a)

b = np.random.normal(loc = 0, scale = 1, size = 5) + 1.0j * np.random.normal(loc = 0, scale = 1, size = 5)
    # define a random complex vector from N(0, 1) (normal distribution of mean 0 and std 1) with size 5
#print("b =",b)

M = np.random.uniform(-1, 1, size = (5, 5)) + 1.0j * np.random.uniform(-1, 1, size = (5, 5))
    # random complex matrix from U[-1, 1] with dimensions 5x5
#print("M =",M)

N = np.random.normal(-1, 1, size = (5, 5)) + 1.0j * np.random.normal(-1, 1, size = (5, 5))
    # random complex matrix from N[-1, 1] with dimensions 5x5
#print("N =",N)

M = M + M.conj().T  # make it Hermitian (all the good matrices are Hermitian, aren't they?)
N = N + N.conj().T

In [50]:
print(a + b)  # point-wise vector addition
print(a - b)  # point-wise vector subtraction
print(a * b)  # point-wise vector multiplication
print(a / b)  # point-wise vector division (be careful here!)

[-0.76380846-0.52315038j -0.34367475+2.03172002j  0.12658317-0.2138789j
  2.95477953+0.39747704j  1.16703984+1.6876804j ]
[ 2.51120531-1.11791859j  0.15317925-2.16953882j -0.92225418-0.67307678j
 -1.18637124-0.91557375j  0.32382302-1.36795664j]
[-1.18667328+1.60345489j  0.16841523-0.18296126j -0.10681033-0.32391067j
  2.00088316+0.04412333j  0.07004022+1.20628306j]
[-0.60461446+0.39128492j -0.02706331+0.04854307j -0.94728533-0.43091931j
  0.35197777-0.23671232j  0.2223423 -0.42654938j]


In [51]:
# scalar products
print(np.dot(a.conj().T, a))  # |a|^2 = (a^*, a)
print(np.dot(a.conj().T, b))  # (a^*, b)

(3.2355389604954294+0j)
(0.11301309221468203+1.0285858825178593j)


In [52]:
# scalar products
print(np.dot(a.conj().T, a))  # |a|^2 = (a^*, a)
print(np.dot(a.conj().T, b))  # (a^*, b)

(3.2355389604954294+0j)
(0.11301309221468203+1.0285858825178593j)


In [53]:
# matrix operations
M + N  # point-wise matrix addition
M - N  # point-wise matrix subtraction
M * N  # point-wise matrix multiplication
M / N  # point-wise matrix division

array([[ 0.08017388-0.j        ,  0.2431183 -0.00762324j,
        -0.23746552-0.06946354j,  0.02932622+0.1783569j ,
        -1.23082817+0.19492853j],
       [ 0.2431183 +0.00762324j, -1.54662651-0.j        ,
         0.0627205 +0.28482604j,  0.91425158-0.34565833j,
        -0.07981144-0.20180558j],
       [-0.23746552+0.06946354j,  0.0627205 -0.28482604j,
        -1.06760147-0.j        ,  0.26662248+0.48152227j,
         0.03486952-0.11304214j],
       [ 0.02932622-0.1783569j ,  0.91425158+0.34565833j,
         0.26662248-0.48152227j,  0.19073386-0.j        ,
         0.15781481-0.02267114j],
       [-1.23082817-0.19492853j, -0.07981144+0.20180558j,
         0.03486952+0.11304214j,  0.15781481+0.02267114j,
        -0.47915325-0.j        ]])

In [54]:
# matrix-vector operations
a.dot(M)  # a.M standard vector-matrix multiplication
np.dot(a, M)  # the same thing

array([-0.93553478+1.54221446j,  0.62090155+0.88174253j,
       -1.17742621-0.52473501j, -1.44451283+1.15261101j,
        0.77256906-1.00160786j])

In [55]:
# matrix-matrix operations
np.dot(M, N)  # M.N matrix multiplication, although np.matmul is more often used for matrix multiplication than np.dot, as is np.einsum (see below)
M.dot(N)  # the same thing

array([[-0.48040008+3.19775513j, -0.3329767 +3.35611861j,
         3.01198043+5.80453639j,  2.49396331+3.91044919j,
        -0.43587737+3.70300841j],
       [-2.69352332+7.34874955j,  2.43513804-2.14343592j,
        -4.60335403+1.16602587j,  2.61667749+5.11587011j,
        -5.52959615-1.3380329j ],
       [-1.16100285+3.70425493j, -4.4902811 -2.75950041j,
        -1.11399317+0.1277699j ,  1.21350733+6.53047434j,
        -2.5659208 -4.56974086j],
       [ 7.97850827-4.17773555j,  4.64511769-3.75869815j,
         5.6315059 -4.5154873j ,  7.48958872-6.03629759j,
         5.96026117-3.85907426j],
       [ 0.36720258-2.54235485j, -7.72800963-0.417j     ,
        -6.52327242+2.84449507j, -3.59421348-3.2260122j ,
        -9.59255022+4.85420849j]])

In [56]:
np.trace(M)  # trace M
np.trace(M.dot(N))  # trace MN

(-1.2622167256784937-8.881784197001252e-16j)

Einstein summation notation and ***np.einsum*** (a **very** useful operation)

Supposing one has two tensors with arbitrarily many indexes (vector, matrix, 3--tensor, ...) $M_{i_1, i_2, \ldots, i_n}$ and $N_{j_1, j_2, \ldots, j_m}$ and writes an expression in the form $\sum\limits_{k_1, k_2, \ldots k_l} M_{i_1, i_2, \ldots, i_n} N_{j_1, j_2, \ldots, j_m}.$

For instance: $$|a|^2 = \sum_i a^{\dagger}_i a_i,\;\text{vector norm},$$
$$b_j = (M a)_j = \sum_k M_{jk} a_k,\;\text{matrix-vector multiplication}$$
$$(MN)_{ij} = \sum_k M_{ik} B_{kj},\;\text{matrix-matrix multiplication}$$
$$(a \otimes b)_{ij} =  a_i b_j,\;\text{outer product}.$$


**Einstein summation notation**: any repeated index implies summation over this index: $$|a|^2 = a^{\dagger}_i a_i,$$, $$b_j = (M a)_j = A_{jk} a_k,$$, $$(MN)_{ij} = M_{ik} B_{kj},$$, $$(a \otimes b)_{ij} =  a_i b_j.$$

In [57]:
#  now several examples of tensor contraction using np.einsum:

np.einsum('i,i->', a.conj(), a)  # |a|^2
np.einsum('i,i->', b.conj(), a)  # b^dag a
np.einsum('ik,kj->ij', M, N)  # M.N matrix-matrix
np.einsum('ik,k->i', M, a)  # M.a matrix-vector
np.einsum('i,j->ij', a, b)  # outer product
np.einsum('ii->', M)  # trace M
np.einsum('ij,ji->', M, N)  # trace MN
np.einsum('i,ij,j->ij', a, M, b)  # M_ij -> M_ij a_i b_j)

# np.einsum is sometimes the fastest way to perform an operation. For instance,
# np.einsum('ij,ji->', M, M) (trace MN) runs in O(N^2) operations, while np.trace(M.dot(N)) in O(N^3) operations

# np.einsum is a Swiss army knife: inside it chooses the fastest numpy implementation for contraction itself

array([[ 0.25617756-0.34615186j, -0.96221706-1.05553866j,
         0.47695873-0.04047082j, -1.97688624-0.76671587j,
         1.30983273-1.78086938j],
       [-0.09399541-0.05756785j,  0.07436416-0.080787j  ,
        -0.04322933+0.03023186j, -0.31916014+0.21268652j,
         0.16482796+0.0241664j ],
       [ 0.63622249+0.27142532j,  0.50362371+0.84974833j,
        -0.15330854-0.46492012j,  0.25348979+1.81704933j,
         0.07116008+0.40904488j],
       [ 0.35613534-1.19698825j, -2.85857151+0.629962j  ,
        -0.73847642+0.1175572j , -1.43808251-0.03171249j,
         0.1738668 -0.24189589j],
       [-0.0812254 -1.47431734j,  1.23633769+0.74185075j,
        -0.03893014-0.18791477j, -0.26705199+0.20690114j,
         0.13630908+2.34761301j]])

In [58]:
np.einsum('ik,ki->',M,N)

(-1.262216725678492+0j)

**Fast slicing**

In [59]:
#  split vector into odd and even index parts:
a = np.arange(10)
even_indexes = np.arange(0, a.shape[0], 2)
odd_indexes = np.arange(1, a.shape[0], 2)

print(a, a[even_indexes], a[odd_indexes])

[0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8] [1 3 5 7 9]


In [60]:
# take the first and the third row of the matrix
#M = np.arange(1, 10).reshape(3, 3)
M[np.array([0, 2]), :]  # this is a new matrix of shape (2,3) containing the first and third rows only of the matrix M

array([[-0.21587877+0.j        , -0.56037457+0.0578489j ,
         0.67474386+0.17711737j, -0.5574161 -0.59376468j,
         0.10070279-1.15935326j],
       [ 0.67474386-0.17711737j, -0.0614416 +0.7814035j ,
         1.4353344 +0.j        , -1.36027672-0.39932848j,
        -0.32393661+0.29732262j]])

In [72]:
#  how about more complex tensors?
A = np.random.uniform(-1, 1, size = (4, 4, 4, 4))  # 4x4x4x4 tensor
print("A",A.shape)
#  take only 1-st and 3-rd indexes in the first index:
B = A[np.array([0, 2]), ...]  # "..." means "full slice in all other dimensions"
print("B",B.shape)
#  take the last index in the 2-nd dimension:
C = A[:, -1, :, :]
print(C.shape)  # the dimensionality reduced

C = A[:, -1:, :, :]  # if want to keep the degenerate dimension
print(C.shape)

#  or
C = A[:, -1, :, :][:, np.newaxis, :, :]  # remove then restore the dimension
print(C.shape)

A (4, 4, 4, 4)
B (2, 4, 4, 4)
(4, 4, 4)
(4, 1, 4, 4)
(4, 1, 4, 4)


Final: **solvers and advanced linear algebra**

In [76]:
eigvals, U = np.linalg.eigh(M)  # diagonalise Hermitian conjugate matrix
print(eigvals.shape, U.shape)
#U[:, i] #contains the i-th eigenvector corresponding to the eigenvalue i (eigvals[i])

#  check that M v_i = lambda_i v_i for all i
print(eigvals)
[np.allclose(U[:, i] * eigvals[i], M.dot(U[:, i])) for i in range(eigvals.shape[0])]
#  actually (eigentlich) eigenvectors!

(5,) (5, 5)
[-2.63295373 -0.89171036  0.90028256  2.34182485  3.17099525]


[True, True, True, True, True]

In [75]:
#  also, the following must hold: U.D.U^{dag} = M
np.allclose(U.dot(np.diag(eigvals)).dot(U.conj().T), M)

True

In [77]:
#  SVD decomposition (required for DQMC)
U, s, V = np.linalg.svd(M, full_matrices = True)
np.allclose(U.dot(np.diag(s)).dot(V), M)

# and may other! LU, QR, et cetera

True

Bonus: **for-loops vs numpy** comparison

In [79]:
a = np.arange(100)
b = np.arange(100)
%timeit [a[i] * b[j] for i in range(100) for j in range(100)]
%timeit np.einsum('i,j->ij', a, b)  # numpy is ~240 times faster

1.96 ms ± 6.46 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
6.39 µs ± 39.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [80]:
M = np.random.uniform(-1, 1, size = (100, 100))
N = np.random.uniform(-1, 1, size = (100, 100))
def prod_naive(M, N):
    C = np.zeros((100, 100))
    for i in range(100):
        for j in range(100):
            for k in range(100):
                C[i, j] += M[i, k] * N[k, j]
    return C
%timeit prod_naive(M, N)
%timeit M.dot(N)  # numpy is ~ 60 times faster

460 ms ± 3.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
121 µs ± 14.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [81]:
def prod_naive(M, a):
    b = np.zeros(100)
    for j in range(100):
        for k in range(100):
            b[j] += M[j, k] * a[k]
    return b
%timeit prod_naive(M, a)
%timeit M.dot(a)  # numpy is ~ 60 times faster

4.19 ms ± 6.18 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.16 µs ± 7.66 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Take home message: **always avoid using pythonic for-loops**, they are **very slow**. You are **very unlikely** to meet any linear algebra operation that can not be done purely within numpy.

**Excercises**: using only numpy routines (for objects creation and manipulation), compute the following: $$\sum\limits_{i=0}^{10} i,\; \sum\limits_{i = 0}^{10} 2^i,\;\sum\limits_{i = 0}^{10} i 2^i,$$

$$\sum\limits_{n=0}^{9} e^{2 \pi i n / 10},\;\sum\limits_{n=0}^{9} e^{2 \pi i n / 10} n,$$

$$a^{\dagger} M a, a = (0, 1, \ldots, 10), M_{ij} = ij.$$

In [84]:
# WRITE SOLUTIONS HERE
sum1 = np.sum(np.arange(11))
sum2 = np.sum(2**(np.arange(11)))
sum3 = np.sum(np.arange(11)*2**(np.arange(11)))
sum4 = np.sum(np.exp(2j*np.pi*np.arange(10)/10))
s = np.arange(10)
sum41 = np.sum(np.exp(2j*np.pi*s/10))
sum5 = np.sum(np.exp(2j*np.pi*np.arange(10)/10)*np.arange(10))
sum51 = np.sum(np.exp(2j*np.pi*s/10)*s)

a = np.arange(11)
M = np.outer(a, a)
a_dagger = a.conj().T
result = a_dagger.dot(M).dot(a)
result2 = np.einsum('i,ij,j->', a_dagger, M, a)


print("sum1:", sum1)
print("sum2:", sum2)
print("sum3:", sum3)
print("sum4:", sum4)
print("sum41:", sum41)
print("sum5:", sum5)
print("sum51:", sum51)
print("result:", result)
print("result2:", result2)


sum1: 55
sum2: 2047
sum3: 18434
sum4: (-3.3306690738754696e-16+1.1102230246251565e-16j)
sum41: (-3.3306690738754696e-16+1.1102230246251565e-16j)
sum5: (-5.000000000000002-15.388417685876266j)
sum51: (-5.000000000000002-15.388417685876266j)
result: 148225
result2: 148225


In [74]:
import numpy as np

# Definiere die Pauli-Matrizen
sigma_x = np.array([[0, 1], [1, 0]])
sigma_y = np.array([[0, -1j], [1j, 0]])
sigma_z = np.array([[1, 0], [0, -1]])

# Einheitsvektor (ex, ey, ez)
e = np.array([1, 0, 0])  # Beispiel: Einheitsvektor in x-Richtung

# Spin-Operator S.e
S_dot_e = (e[0] * sigma_x + e[1] * sigma_y + e[2] * sigma_z) * (1/2)

print("Pauli-Matrizen:")
print("sigma_x:\n", sigma_x)
print("sigma_y:\n", sigma_y)
print("sigma_z:\n", sigma_z)

print("\nEinheitsvektor e:", e)

print("\nResultierende 2x2-Matrix S.e:")
print(S_dot_e)

Pauli-Matrizen:
sigma_x:
 [[0 1]
 [1 0]]
sigma_y:
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
sigma_z:
 [[ 1  0]
 [ 0 -1]]

Einheitsvektor e: [1 0 0]

Resultierende 2x2-Matrix S.e:
[[0. +0.j 0.5+0.j]
 [0.5+0.j 0. +0.j]]
