In [1]:
import numpy as np

## Reshaping

We can convert a matrix to an array using  `np.reshape`

In [2]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(M)
print(np.reshape(M, -1))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


We can also use  `np.reshape` to modify the dimensions of $M$. Here we convert the $2 \times 4$ matrix to a $2 \times 2 \times 2$ tensor

In [5]:
X = np.reshape(M, [2, 2, 2])
print(X[0,:,:])
print(X[1,:,:])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


The default order is row-major. One can change it by inserting the option 'F'.

In [4]:
#Try
#X = np.reshape(M, [2, 2, 2],order='F')
#print(X[0,:,:])
#print(X[1,:,:])

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


Access to $M$ elements

In [6]:
print(X[1, 0, 1])
print(np.reshape(M, -1)[1*4 + 0*2 + 1*1])

6
6


In [7]:
X[1, 0, 1] = 42
print(M) # The original is modified. Reshaping provides a new view of the same data (usually).

[[ 1  2  3  4]
 [ 5 42  7  8]]


## `np.tensordot` and `np.transpose`

In [8]:
s_plus = np.array([[0,0], [1,0]])
s_minus = np.array([[0,1], [0,0]])


M = np.zeros((2, 2, 2))
M[0,:,:] = s_plus
M[1,:,:] = s_minus
"""    ┏━━━┓
M = 1 ━┫   ┣━ 2
       ┗━┳━┛
         0
"""


N = np.tensordot(M, M, axes=(2, 1))

"""    ┏━━━┓ ┏━━━┓
N = 1 ━┫ M ┣━┫ M ┣━ 3
       ┗━┳━┛ ┗━┳━┛
         0     2
"""


N = np.transpose(N, [0,2,1,3])
"""    ┏━━━┓ ┏━━━┓
N = 2 ━┫ M ┣━┫ M ┣━ 3
       ┗━┳━┛ ┗━┳━┛
         0     1
"""


N = np.trace(N, axis1=0, axis2=1)
"""    ┏━━━┓ ┏━━━┓
N = 0 ━┫ M ┣━┫ M ┣━ 1
       ┗━┳━┛ ┗━┳━┛
         ┗━━━━━┛
"""


# We could also do this with a single tensordot:
N2 = np.tensordot(M, M, axes=([2, 0], [1, 0]))
assert(np.all(N == N2))

## Reshape + SVD

In [9]:
M = np.zeros((2, 2, 2))
M[0,:,:] = s_plus
M[1,:,:] = s_minus
"""    ┏━━━┓
M = 1 ━┫   ┣━ 2
       ┗━┳━┛
         0
"""


M_reshaped = np.reshape(M, [2*2, 2])
"""          ┏━━━┓
M_reshaped = ┃   ┣━ 1
             ┗┳━┳┛
              0 0
"""


U, S, Vh = np.linalg.svd(M_reshaped, full_matrices=False)
"""
 ┏━━━┓      ┏━━━┓ ┏━━━┓ ┏━━━━┓
 ┃   ┣━ 1 = ┃ U ┣━┫ S ┣━┫ Vh ┣━ 1
 ┗┳━┳┛      ┗┳━┳┛ ┗━━━┛ ┗━━━━┛
  0 0        0 0
"""


A = np.reshape(U, [2, 2, 2])
"""┏━━━┓         ┏━━━┓ ┏━━━┓ ┏━━━━┓
1 ━┫ M ┣━ 2 = 1 ━┫ A ┣━┫ S ┣━┫ Vh ┣━ 2
   ┗━┳━┛         ┗━┳━┛ ┗━━━┛ ┗━━━━┛
     0             0
"""

# Check the normalization
X = np.zeros((2, 2))
for s in range(2):
    X += A[s,:,:].T.conj() @ A[s,:,:]

print(X)

[[1. 0.]
 [0. 1.]]
