In [9]:
import numpy as np

## 1.1
The MPS tensors for the GHZ state are given as follows
- at the left hand side boundary: $M^{[1]}_{\uparrow}=\frac{1}{\sqrt{2}}\begin{pmatrix} 1 & 0 \end{pmatrix}$, $M^{[1]}_{\downarrow}=\frac{1}{\sqrt{2}}   \begin{pmatrix} 0 & 1 \end{pmatrix}$
- at all the intermediate sites $i=2,...,N-1$:  $M^{[i]}_{\uparrow}=\begin{pmatrix} 1 & 0 \\ 0 & 0\end{pmatrix}$, $M^{[i]}_{\downarrow}=\begin{pmatrix} 0 & 0 \\ 0 & 1\end{pmatrix}$ 
- at the right hand side boundary: $M^{[N]}_{\uparrow}=\begin{pmatrix} 1  \\ 0 \end{pmatrix}$, $M^{[N]}_{\downarrow}=   \begin{pmatrix} 0 \\ 1 \end{pmatrix}$;


In this way, all the states different from $|111...1>$ and $|000...0>$ have weight equal to 0. 

We can derive the solution for $|\Psi_1\rangle$ modifying the construction above. In this case, we only have to allow for the two states
\begin{equation}
|10101...0>, \quad |01010...1>
\end{equation}
if the number of spins $N$ is even, or for
\begin{equation}
|10101...1>, \quad |01010...0>
\end{equation}
if $N$ is odd.
It follows that:
- at the left hand side boundary:  
$M^{[1]}_{\uparrow}=\frac{1}{\sqrt{2}}\begin{pmatrix} 1 & 0 \end{pmatrix}$, $M^{[1]}_{\downarrow}=\frac{1}{\sqrt{2}}   \begin{pmatrix} 0 & 1 \end{pmatrix}$

- at the right hand side boundary:
1) for number of spins $N$ odd -> $M^{[N]}_{\uparrow}=\begin{pmatrix} 1 \\ 0\end{pmatrix}$, $M^{[N]}_{\downarrow}=\begin{pmatrix} 0 \\ 1\end{pmatrix}$

2) for number of spins $N$ even -> $M^{[N]}_{\uparrow}=\begin{pmatrix} 0 \\ 1\end{pmatrix}$, $M^{[N]}_{\downarrow}=\begin{pmatrix} 1 \\ 0\end{pmatrix}$.

At an even site $i$ mod $2=0$, the tensor $M^{[i]}_{\sigma_i}$ is specified by: $M^{[i]}_{\uparrow}=\begin{pmatrix} 0 & 0 \\ 0 & 1\end{pmatrix}$, $M^{[i]}_{\downarrow}=\begin{pmatrix} 1 & 0 \\ 0 & 0\end{pmatrix}$.

At an odd site $i$ mod $2=1$, the tensor $M^{[i]}_{\sigma_i}$ is specified by: $M^{[i]}_{\uparrow}=\begin{pmatrix} 1 & 0 \\ 0 & 0\end{pmatrix}$, $M^{[i]}_{\downarrow}=\begin{pmatrix} 0 & 0 \\ 0 & 1\end{pmatrix}$.



# Exercise 1

Note: in this exercise the numeration of the sites starts from 1. Consider that, in the numerical implementation in exercise 2, the first site is 0, so the role of matrices at even and odd sites will be reversed.

## 1.2
For the state $|\Psi_2\rangle$, we notice that it is a superposition of all the possible spin configurations in the basis. Moreover, the coefficients of all the computational basis states $|s_1, ...s_N\rangle$ (spin-configuration) are equal to $(\frac{1}{\sqrt{2}})^{N}$. Therefore, we can find a representation with bond dimension $d=1$: $M^{[i]}_{\sigma_i}=\frac{1}{\sqrt{2}}$. Indeed, this choice satisfies the constraint $\sum_{\sigma_i} M^{[i]\dagger}_{\sigma_i} M^{[i]}_{\sigma_i} = 1$ for all $i$.

## 1.3.
In the canonical form, the following properties (left- and right-normalization) should be fulfilled

$\sum \limits_{\sigma_i}(A^{[i]\sigma_i})^{\dagger} A^{[i]\sigma_i}=I$ with $A^{[i]\sigma_i}=\Lambda^{[i-1]}\Gamma^{[i]\sigma_{i}}$, $A^{[1]\sigma_1}=\Gamma^{[1]\sigma_{1}}$, $\ \ \ (1)$

as well as

$\sum \limits_{\sigma_i}B^{[i]\sigma_i}(B^{[i]\sigma_i})^{\dagger}=I$ with $B^{[i]\sigma_i}=\Gamma^{[i]\sigma_i}\Lambda^{[i]}$, $B^{[N]\sigma_N}=\Gamma^{[i]\sigma_i}$. $\ \ \ (2)$

The canonical form is easy to guess for $|\Psi_1\rangle$ and $|\Psi_2\rangle$. In particular, for
$|\Psi_1\rangle$ with MPS representation $[M^{[1]\sigma_1},...M^{[N]\sigma_N}]$ stated in 1.1, the matrices $[\Gamma^{[1]\sigma_1}, ...\Gamma^{[N]\sigma_N}]$, $[\Lambda^{[1]}, ...\Lambda^{[N-1]}]$ are given by

$\Gamma^{[i]\sigma_i}=\sqrt{2}M^{[i]\sigma_i}$ for $i \neq 1,N$

and at the boundaries

$\Gamma^{[1]\uparrow}=\begin{pmatrix} 1 & 0 \end{pmatrix}$, $\Gamma^{[1]\downarrow}=\begin{pmatrix} 0 & 1 \end{pmatrix}$,
$\Gamma^{[N]\sigma_N}=M^{[N]\sigma_N}$.

The singular values are $\Lambda^{[i]}=\begin{pmatrix} \frac{1}{\sqrt{2}} & 0 \\ 0 & \frac{1}{\sqrt{2}} \end{pmatrix}$.

Plugging the found tensors into conditions (1), (2) we can confirm that they are fulfilled.


The canonical form of the state $|\Psi_2\rangle$ is given by

$\Gamma^{[i]\sigma_i}=\frac{1}{\sqrt{2}}$ and singular (Schmidt) values $\Lambda^{[i]}=1$.


## 1.4 (Optional)
We can find an MPO representation of the Heisenberg model with bond dimension $d=5$

$O^{[i]}=\begin{pmatrix}  I & 0 & 0 & 0 & 0 \\ S^{x}_i & 0 & 0 & 0 & 0 \\ S^{y}_i & 0 & 0 & 0 & 0 \\ S^{z}_i & 0 & 0 & 0 & 0 \\ 0 & -JS^{x}_{i}& -JS^{y}_{i}& -JS^{z}_{i} & I \end{pmatrix}$

with boundary tensors
$O^{[1]}=\begin{pmatrix}   0 & -JS^{x}_{1}& -JS^{y}_{1}& -JS^{z}_{1} & I \end{pmatrix}$

and  

$O^{[N]}=\begin{pmatrix}  I  \\ S^{x}_N \\ S^{y}_N \\ S^{z}_N \\ 0 \end{pmatrix}$

# Exercise 2
Throughout this exercise we will use the following labelling of legs:
![title](labelling.png)

We will also be using the convention that we include trivial (i.e., one-dimensional) "phantom" singular values at either end of the MPS chain.

## 2.1

The first step is to implement functions that, given a MPS representation $M = [M^{[1]\sigma_1} , . . . ,M^{[N]\sigma_N}]$, compute the left-normalized
representation $[A^{[1]}, . . . ,A^{[n]}]$ and the right-normalized representation $[B^{[1]}, . . . ,B^{[n]}]$.

In [ ]:
def left_normalize(Ms):
    """
    Convert a MPS to a left-normalized MPS.

    Parameters
    ----------
    Ms : list of rank 3 tensors.
        A MPS representation of the state.

    Returns
    -------
    As : list of rank 3 tensors.
        A left-normalized MPS representation of the state.
    """

    As = []
    T = np.ones((1, 1))
    for M in Ms:
        M = np.tensordot(T, M, axes=(1, 1)) 
        M = np.transpose(M, [1, 0, 2])
        d, chi1, chi2 = M.shape             
        U, S, Vh = np.linalg.svd(np.reshape(M, [d*chi1, chi2]), full_matrices=False)
        A = np.reshape(U, [d, chi1, -1])   
        As.append(A)                        
        T = np.diag(S) @ Vh                 

    # Keep leftover signs (but no normalization)
    As[0] = As[0]*np.sign(T)
    return As

def right_normalize(Ms):
    """
    Convert a MPS to a right-normalized MPS.

    Parameters
    ----------
    Ms : list of rank 3 tensors.
        A MPS representation of the state.

    Returns
    -------
    Bs : list of rank 3 tensors.
        A right-normalized MPS representation of the state.
    """

    Bs = []
    T = np.ones((1, 1))
    for M in reversed(Ms):
        M = np.tensordot(M, T, axes=(2, 0))
        d, chi1, chi2 = M.shape
        M = np.transpose(M, [1, 0, 2])
        U, S, Vh = np.linalg.svd(np.reshape(M, [chi1, d*chi2]), full_matrices=False)
        B = np.transpose(np.reshape(Vh, [-1, d, chi2]), [1, 0, 2])

        Bs.append(B)
        T = U @ np.diag(S)

    # reverse Bs
    Bs = Bs[::-1]
    # Keep leftover signs (but no normalization)
    Bs[0] = Bs[0]*np.sign(T)
    return Bs



## 2.2

Implement a function that constructs the Vidal canonical form and returns the matrices $\Gamma = [\Gamma^{[1]\sigma_1} , . . . ,\Gamma^{[N]\sigma_N}]$ and $\Lambda = [\Lambda^{[1]} , . . . ,\Lambda^{[N-1]}]$.

In [17]:
def truncate(U, S, Vh):
    """
    Remove singular values below threshold.
    """

    l = np.sum(np.abs(S) > 1e-8)
    return U[:, :l], S[:l], Vh[:l, :]

def vidal_form(Ms):
    """
    Convert a MPS to Vidal canonical form.

    Parameters
    ----------
    Ms : list of rank 3 tensors.
        A MPS representation of the state.

    Returns
    -------
    Lambdas : list of rank 1 tensors.
        The Schmidt values of every site.

    Gammas : list of rank 3 tensors.
        The Gamma matrices in the Vidal canonical form.
    """

    Lambdas = [np.array([1])]
    Gammas = []
    Bs = right_normalize(Ms)
    N = len(Bs)
    T = np.ones((1, 1))
    for i in range(N):
        Bi = np.tensordot(T, Bs[i], axes=(1, 1))
        Bi = np.transpose(Bi, [1, 0, 2])
        d, chi1, chi2 = Bi.shape
        U, S, Vh = truncate(*np.linalg.svd(np.reshape(Bi, [d*chi1, chi2]), full_matrices=False))

        A = np.reshape(U, [d, chi1, len(S)])
        Gamma = np.tensordot(np.diag(1.0/Lambdas[-1]), A, axes=(1, 1))
        Gammas.append(Gamma.transpose([1, 0, 2]))
        Lambdas.append(S)
        T = np.diag(S)@Vh

    return Lambdas, Gammas

You can use the implemented functions to get the Vidal's canonical form for states $|\Psi_1>$ and $|\Psi_2>$. 

Given the two MPS forms found in exercise 1.1 and 1.2, one can apply the canonization procedure implemented above.

In [18]:
def phi1(N):
    """
    Get MPS form of phi1.

    Parameters
    ----------
    N : int
        The number of sites.

    Returns
    -------
    Lambdas
        The Schmidt values of phi1.

    Gammas
        The Gamma matrices in the Vidal canonical form of phi1.
    """

    M0 = np.zeros((2, 1, 2))
    M0[0,:,:] = [1, 0]/np.sqrt(2)
    M0[1,:,:] = [0, 1]/np.sqrt(2)
    if N % 2 == 0:
        MN = np.zeros((2, 2, 1)) #MN is actually the matrix at site N-1
        MN[0,:,:] = np.vstack([0, 1]) 
        MN[1,:,:] = np.vstack([1, 0])
    else:
        MN = np.zeros((2, 2, 1))
        MN[0, :] = np.vstack([1, 0])
        MN[1, :] = np.vstack([0, 1])

    M_even = np.zeros((2, 2, 2))
    M_even[0,:,:] = [[1, 0], [0, 0]]
    M_even[1,:,:] = [[0, 0], [0, 1]]
    
    M_odd = np.flip(M_even, 0)

    Ms = [M0]
    for i in range(1, N - 1):
        if i % 2 == 0:
            Ms.append(np.copy(M_even))
        else:
            Ms.append(np.copy(M_odd))

    Ms.append(MN)
    return vidal_form(Ms)

def phi2(N):
    """
    Get MPS form of phi2.

    Parameters
    ----------
    N : int
        The number of sites.

    Returns
    -------
    Lambdas
        The Schmidt values of phi2.
        
    Gammas
        The Gamma matrices in the Vidal canonical form of phi2.
    """

    M0 = np.zeros((2, 1, 2))
    M0[0, :] = [1, 0]
    M0[1, :] = [1, 0]
    
    M = np.zeros((2, 2, 2))
    M[0] = np.identity(2)
    M[1] = np.identity(2)
    
    MN = np.transpose(M0, [0, 2, 1])

    Ms = [M0/np.sqrt(2)]
    for i in range(N - 2):
        Ms.append(np.copy(M)/np.sqrt(2))

    Ms.append(MN/np.sqrt(2))
    return vidal_form(Ms)

In [ ]:
N = 10
Lambdas1, Gammas1 = phi1(N)
Lambdas2, Gammas2 = phi2(N)
print(Gammas1[7]) #up to this point everything is fine
print(Gammas1[8]) #here something not clear happens. The matrices at
#this site simply are not the ones one would expect (according
#to my understanding the rows are exchanged for some reason)
print(Gammas1[9]) #it should be with the two gammas reversed or rows
# exchanged 


10
[[[0.         0.        ]
  [0.         1.41421356]]

 [[1.41421356 0.        ]
  [0.         0.        ]]]
[[[ 0.         -1.41421356]
  [ 0.          0.        ]]

 [[ 0.          0.        ]
  [-1.41421356  0.        ]]]
[[[1.]
  [0.]]

 [[0.]
  [1.]]]


## 2.4
Write a function that, given two generic states in the Vidal's canonical form, evaluates their overlap as describe in the exercise sheet. Then, calculate the overlap between $|\Psi_1>$ and $|\Psi_2>$ for N = 30 spins.

In [24]:
def overlap(Lambdas1, Gammas1, Lambdas2, Gammas2):
    """
    Compute the overlap of two wave functions given in Vidal canonical form.

    Parameters
    ----------
    Lambdas1 : list of rank 1 tensors.
        Schmidt values of the first state.

    Gammas1 : list of rank 3 tensors.
        Gamma matrices of the first state.

    Lambdas2 : list of rank 1 tensors.
        Schmidt values of the second state.

    Gammas2 : list of rank 3 tensors.
        Gamma matrices of the second state.

    Returns
    -------
    complex
        Overlap of the two states
    """

    assert(len(Gammas1) == len(Gammas2))

    overlap = np.tensordot(Gammas2[0], Gammas1[0].conj(), axes=(0, 0))
    overlap = np.transpose(overlap, [0, 2, 1, 3])
    for i in range(1, len(Gammas1)):
        # Multiply Lambdas
        overlap = np.tensordot(overlap, np.diag(Lambdas2[i]), axes=(2, 0))
        overlap = np.tensordot(overlap, np.diag(Lambdas1[i]), axes=(2, 0))
        
        # Multiply Gammas
        overlap = np.tensordot(overlap, Gammas2[i], axes=(2, 1))
        overlap = np.tensordot(overlap, Gammas1[i].conj(), axes=([2,3], [1, 0]))

    return overlap.flatten()[0]

In [25]:
N = 30
Lambdas1, Gammas1 = phi1(N)
Lambdas2, Gammas2 = phi2(N)
print("Numeric:   ", overlap(Lambdas1, Gammas1, Lambdas2, Gammas2))
print("Analytical:", 2*1/np.sqrt(2)*1/np.sqrt(2)**N)

Numeric:    4.315837287515538e-05
Analytical: 4.31583728751554e-05


Verify the correct implementation of your function by calculating the normalization of an arbitrary MPS state in canonical form (should be equal to 1).

In [22]:
def random_MPS(d, N):
    """
    returns random MPS with bond dimension d
    """
    A1 = np.random.rand(2,1,d)
    Ms = [A1]
    for i in range(N - 2):
        Ai=np.random.rand(2,d,d) 
        Ms.append(Ai)

    An = np.random.rand(2,d,1)
    Ms.append(An)
    return Ms

def check_left_normalisation(A):
    """
    returns True, if A is right-normalized. 
    Only yields true result if rank of singular values not smaller than bond dimension.
    has to be modified!
    """
    E = np.tensordot(A, np.conjugate(A), axes=([0, 1], [0, 1]))
    return np.linalg.norm(E - np.eye(np.shape(E)[0])) < 1e-4

def check_right_normalisation(A):
    """
    returns True, if A is right-normalized. 
    Only yields true result if rank of singular values not smaller than bond dimension.
    has to be modified!
    """
    E = np.tensordot(A, np.conjugate(A), axes=([0, 2], [0, 2]))
    return np.linalg.norm(E - np.eye(np.shape(E)[0])) < 1e-4

def check_properties(Lambdas, Gammas):
    properties = True
    for i in range(len(Gammas)):
        A = np.tensordot(np.diag(Lambdas[i]), Gammas[i], axes=(1, 1))
        A = np.transpose(A, [1, 0, 2])
        B = np.tensordot(Gammas[i], np.diag(Lambdas[i+1]), axes=(2, 0))
        properties = properties and check_left_normalisation(A) and check_right_normalisation(B)

    return properties

Lambdas_rand, Gammas_rand = vidal_form(random_MPS(2, 30))
print("Norm:", overlap(Lambdas_rand, Gammas_rand, Lambdas_rand, Gammas_rand))
print("Is canonical:", check_properties(Lambdas_rand, Gammas_rand))

Norm: 1.0000000000000007
Is canonical: True
